apiVersion: v1
kind: Secret
metadata:
  name: chatapp-secrets
  namespace: chat-app
type: Opaque
data:
  jwt: ZWFjMzBjOGU1NTVmZWFkMDg3MzFlNzM5OTQwMjcyNDc1MTBiOWUwMjdlZThmYTJmMzEwOGU1NmQ1M2E0ZGFlNWZlOWU5Y2IzNGI3NzYxZjJlMDYwZDcyZTA1NDMyNTIxMTc1Mjc3ZWU4YTYwMzQxMzg5ZjdmNGQwNGY1ZjMxYmM=
